"""GitHub Automation Service - PR generation and management."""
import httpx
from dataclasses import dataclass
from backend.shared.config import get_settings
import structlog

settings = get_settings()
logger = structlog.get_logger()


@dataclass
class PRContent:
    title: str
    body: str
    branch_name: str
    file_changes: list[dict]  # [{"path": "...", "content": "..."}]
    labels: list[str]
    reviewers: list[str]


class GitHubAutomationService:
    """Generates code fixes and creates Pull Requests."""

    def __init__(self):
        self.base_url = "https://api.github.com"
        self.headers = {
            "Authorization": f"token {settings.GITHUB_TOKEN}",
            "Accept": "application/vnd.github.v3+json",
        }

    async def generate_fix(self, incident_context: dict) -> PRContent:
        """Generate a code/config fix based on RCA results."""
        root_cause = incident_context.get("root_cause", "")
        service = incident_context.get("service_name", "")
        remediation = incident_context.get("remediation_steps", [])
        
        # Use LLM to generate the actual fix
        fix_content = await self._generate_code_fix(root_cause, service, remediation)
        
        return PRContent(
            title=f"fix({service}): auto-remediation for incident {incident_context.get('incident_id', '')}",
            body=self._build_pr_body(incident_context),
            branch_name=f"aiops/fix-{incident_context.get('incident_id', 'unknown')[:8]}",
            file_changes=fix_content,
            labels=["aiops-generated", "auto-fix", incident_context.get("severity", "P2")],
            reviewers=incident_context.get("reviewers", []),
        )

    async def create_pull_request(self, repo: str, pr_content: PRContent, base_branch: str = "main") -> dict:
        """Create a PR on GitHub with the generated fix."""
        async with httpx.AsyncClient(headers=self.headers, timeout=30.0) as client:
            # 1. Get latest commit SHA
            ref_resp = await client.get(f"{self.base_url}/repos/{repo}/git/ref/heads/{base_branch}")
            ref_resp.raise_for_status()
            base_sha = ref_resp.json()["object"]["sha"]

            # 2. Create branch
            await client.post(
                f"{self.base_url}/repos/{repo}/git/refs",
                json={"ref": f"refs/heads/{pr_content.branch_name}", "sha": base_sha},
            )

            # 3. Create/update files
            for file_change in pr_content.file_changes:
                await client.put(
                    f"{self.base_url}/repos/{repo}/contents/{file_change['path']}",
                    json={
                        "message": f"fix: {pr_content.title}",
                        "content": self._encode_content(file_change["content"]),
                        "branch": pr_content.branch_name,
                    },
                )

            # 4. Create PR
            pr_resp = await client.post(
                f"{self.base_url}/repos/{repo}/pulls",
                json={
                    "title": pr_content.title,
                    "body": pr_content.body,
                    "head": pr_content.branch_name,
                    "base": base_branch,
                },
            )
            pr_resp.raise_for_status()
            pr_data = pr_resp.json()

            # 5. Add labels and reviewers
            pr_number = pr_data["number"]
            if pr_content.labels:
                await client.post(
                    f"{self.base_url}/repos/{repo}/issues/{pr_number}/labels",
                    json={"labels": pr_content.labels},
                )
            if pr_content.reviewers:
                await client.post(
                    f"{self.base_url}/repos/{repo}/pulls/{pr_number}/requested_reviewers",
                    json={"reviewers": pr_content.reviewers},
                )

            logger.info("PR created", repo=repo, pr_number=pr_number)
            return {
                "pr_url": pr_data["html_url"],
                "pr_number": pr_number,
                "status": "created",
            }

    def _build_pr_body(self, context: dict) -> str:
        return f"""## 🤖 AI-Generated Fix

**Incident:** {context.get('incident_id', 'N/A')}
**Service:** {context.get('service_name', 'N/A')}
**Severity:** {context.get('severity', 'N/A')}

### Root Cause
{context.get('root_cause', 'Unknown')}

### Confidence Score
{context.get('confidence', 0):.0%}

### Risk Analysis
- **Risk Level:** Low
- **Rollback:** Revert this commit
- **Testing:** Unit tests pass, integration tests recommended

### ⚠️ Human Review Required
This PR was automatically generated by the AIOps platform. Please review carefully before merging.

---
*Generated by AIOps Platform v1.0*
"""

    async def _generate_code_fix(self, root_cause: str, service: str, remediation: list) -> list[dict]:
        """Use LLM to generate actual code fix."""
        # In production: call Ollama to generate the fix
        return [{"path": f"config/{service}/settings.yaml", "content": "# AI-generated fix\n"}]

    def _encode_content(self, content: str) -> str:
        import base64
        return base64.b64encode(content.encode()).decode()
